version: '3.8'

services:
  nestjs_starter_postgres: # Needs updating
    image: postgres:alpine
    container_name: nestjs_starter_postgres # Needs updating
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - nestjs_starter_postgres_data:/var/lib/postgresql/data # Needs updating

networks:
  default:
    name: nestjs_starter # Needs updating

volumes:
  nestjs_starter_postgres_data: # Needs updating
