name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches: ['*']

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Run tests
        run: pnpm test

# This job is for end-to-end tests, currently don't know how to run them
# in github actions.
#
#  e2e-tests:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/actions/build
#      - name: Run tests
#        run: pnpm test:e2e
#        env:
#          POSTGRES_USER: username
#          POSTGRES_PASSWORD: password